baseurl = "https://davidbernad.com/"
title = "David Bernad Website"
DefaultContentLanguage = "en"
googleAnalytics = "UA-XXXXXXXX-Y"

[params]
    # Meta
    description = "David portfolio"
    author = "David"

    # Social
    GithubID = "nazhor"
    ItchioID= "nazhor"
    LinkedInID = "david-bernad-sanz-4877549a/"
    Name = "David Bernad"
    HeaderUsername = "dbernad"
    HeaderHostname = "nazhor"
    Email = "contact@davidbernad.com"
    ProfilePicture = "/images/amaze.jpg"

[languages]
    [languages.en]
        [languages.en.params]
            languageName = "EN"
            About = "Welcome! I'm David, software and game developer. Please, come in, take a look and if you find something you like, don't hesitate to contact me."
            # [languages.en.menu]
            #   [[languages.en.menu.header]]
            #     name = "projects"
            #     weight = 1
            #     url = "/projects"
            #   [[languages.en.menu.header]]
            #     name = "about"
            #     weight = 0
            #     url = "/about"
    [languages.es]
        [languages.es.params]
            languageName = "ES"
            About = "¡Bienvenido! Mi nombre es David, desarrollador de software y videojuegos. Por favor, pasa, echa un vistazo y si ves algo que te gusta, no dudes en contactarme."
            # [languages.es.menu]
            #   [[languages.es.menu.header]]
            #     name = "proyectos"
            #     weight = 1
            #     url = "/projects"
            #   [[languages.es.menu.header]]
            #     name = "sobre_mí"
            #     weight = 0
            #     url = "/about"