baseurl = "https://davidbernad.com/"
#For testing
# baseurl = "https://davidbernad.com/portfolio_david/"
title = "David Bernad Website"
DefaultContentLanguage = "en"
googleAnalytics = "UA-XXXXXXXX-Y"

publishdir = "docs"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    # Meta
    description = "David portfolio"
    author = "David"
    name ="David Bernad"

    # Social
    GithubID = "nazhor"
    CodepenID = "nazhor"
    ItchioID= "nazhor"
    LinkedInID = "david-bernad-sanz-4877549a/"
    Email = "contact@davidbernad.com"

    ProfilePicture = "/images/photo.jpg"
    #For testing
    # ProfilePicture = "images/photo.jpg"

[languages]
    [languages.en]
        [languages.en.params]
            languageName = "EN"
            About = "Hello! I'm David, software and game developer with nearly ten years of working experience. Currently I combine my day job as a software developer in a company that develops video management systems, with my passion for making games. Here you can find links to my differents profiles and also a tiny sample of some of my work. Please, come in, take a look and if you find something you like, don't hesitate to contact me."
            AboutButton = "Home"
            ProjectsButton = "Projects"
            TagAll = "*"
            TagGames = "Video games"
            TagSoft = "Software"
            TagOther = "Other"
    [languages.es]
        [languages.es.params]
            languageName = "ES"
            About = "¡Hola! Mi nombres es David, desarrollador de software y videojuegos con casi diez años de experiencia laboral. Actualmente combino mi trabajo de día en una empresa que crea sistemas de videovigilancia, con mi pasión por crear juegos. Aquí puedes encontrar enlaces a mis diferentes perfiles asi como una pequeña muestra de mi trabajo. Por favor, pasa, echa un vistazo y si ves algo que te gusta, no dudes en contactarme."
            AboutButton = "Home"
            ProjectsButton = "Proyectos"
            TagAll = "*"
            TagGames = "Videojuegos"
            TagSoft = "Software"
            TagOther = "Otros"